[build]
  command = "yarn install --frozen-lockfile && yarn workspace client build"
  publish = "client/dist"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
